sudo: false
language: node_js
node_js:
  - "0.10"
# Handle git submodules yourself
git:
    submodules: false
after_script:
  - npm install coveralls
  - cat build/coverage/*/lcov.info | ./node_modules/.bin/coveralls
