sudo: false
language: node_js
node_js:
  - "0.10"
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
after_script:
  - npm install coveralls
  - cat build/coverage/*/lcov.info | ./node_modules/.bin/coveralls
