sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - bower_components
node_js:
  - "stable"
# Handle git submodules yourself
git:
    submodules: false
after_script:
  - npm install coveralls
  - cat build/coverage/*/lcov.info | ./node_modules/.bin/coveralls
